quick update

diff --git a/scripts/lyrics b/scripts/lyrics
--- a/scripts/lyrics
+++ b/scripts/lyrics
@@ -21,7 +21,7 @@ function doit {
     U=$(curl -s "https://search.azlyrics.com/search.php?q=$Q")
     U=$(echo "$U" | sed -rn 's/.* 1\. <a href="(.+).html" .+/\1.html/p')
     O=$(lynx -cfg=<(echo 'CHARACTER_SET:UNICODE (UTF-8)') -dump "$U")
-    S=$(echo "$O" | strbetweenlines 'Print' 'Submit Corrections')
+    S=$(echo "$O" | strbetweenlines 'Print' '\[')
     [[ "$S" = '' ]] && echo "ERROR on Q='$Q', U='$U'" && exit 1
     echo "$S" | fribidi --nopad
 }
@@ -62,10 +62,10 @@ if [[ "$Q" = '' ]] || [[ "$SET" = 1 ]]; then
     }
     Q="$T by $A"
     R=$(doit "$Q")
+    echo "$R" | grep -q 'ERROR on' && exit 1
     echo "$R" > "$LF"
     echo "$R" | more
 else
     doit "$Q" | more
 fi
-
 
