quick update

diff --git a/scripts/office2007 b/scripts/office2007
--- a/scripts/office2007
+++ b/scripts/office2007
@@ -4,8 +4,7 @@
 
 JAIL="$HOME/Firejail/office2007"
 SETUP='office2007'
-INSTALLER="/mnt/hdd2/GoodStuff2/Things/ms office/$SETUP"
-P="$HOME/.wine/drive_c/Program Files/Microsoft Office/Office12"
+INSTALLER="/mnt/hdd1/Public/software/non-free-software/Microsoft/office/$SETUP"
 
 LINE='==================================='
 
@@ -16,6 +15,15 @@ info() {
     echo $LINE
 }
 
+err() {
+    {
+        echo $LINE
+        printf '\033[1m\033[31mERROR:\033[0m '
+        echo "$@"
+        echo $LINE
+    } >&2
+}
+
 needed() {
     echo $LINE
     printf '\033[1;33mNEEDED:\033[0m '
@@ -23,9 +31,13 @@ needed() {
     echo $LINE
 }
 
-if [ ! -d "$JAIL" ]; then
-    info 'Not installed! Installing...' &&
-        rm -rf "$JAIL" &&
+install() {
+    info 'Not installed! Installing...'
+    [ -d "$INSTALLER" ] || {
+        err "Installer directory not found at $INSTALLER"
+        return 1
+    }
+    rm -rf "$JAIL" &&
         mkdir -p "$JAIL" &&
         info 'Setting up Wine and installing fonts' &&
         needed 'Once done, set the Windows version to Windows XP' &&
@@ -40,19 +52,28 @@ winetricks corefonts" &&
         info 'Cleaning...' &&
         rm -rf "$JAIL/$SETUP" &&
         info 'DONE!'
-fi
+}
 
-if [ "$2" ]; then
-    rm -rf "$JAIL/tmpdocs/"
-    mkdir "$JAIL/tmpdocs/"
-    cp "$2" "$JAIL/tmpdocs/"
-    ARG="$HOME/tmpdocs/$(basename "$2")"
-fi
+main() {
+    if [ ! -d "$JAIL" ]; then
+        install || exit
+    fi
 
-case "$1" in
-    w*) APP="WINWORD";;
-    e*) APP="EXCEL";;
-    p*) APP="POWERPNT";;
-esac
+    if [ "$2" ]; then
+        rm -rf "$JAIL/tmpdocs/"
+        mkdir "$JAIL/tmpdocs/"
+        cp "$2" "$JAIL/tmpdocs/"
+        ARG="$HOME/tmpdocs/$(basename "$2")"
+    fi
 
-firejail-my office2007 wine "$P/$APP.EXE" "$ARG" #2>/dev/null
+    case "$1" in
+        w*) APP="WINWORD";;
+        e*) APP="EXCEL";;
+        p*) APP="POWERPNT";;
+    esac
+
+    P="$HOME/.wine/drive_c/Program Files/Microsoft Office/Office12"
+    firejail-my office2007 wine "$P/$APP.EXE" "$ARG" #2>/dev/null
+}
+
+main "$@"
